"""create user topic progress table

Revision ID: 61ebcd01ea61
Revises: b9bd36bba633
Create Date: 2026-09-15 00:56:40.176842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ebcd01ea61'
down_revision: Union[str, Sequence[str], None] = 'b9bd36bba633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_topic_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('questions_solved', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('wrong_answers', sa.Integer(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_user_topic_progress')
    )
    op.create_index(op.f('ix_user_topic_progress_id'), 'user_topic_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_topic_progress_topic_id'), 'user_topic_progress', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_topic_progress_user_id'), 'user_topic_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_topic_progress_user_id'), table_name='user_topic_progress')
    op.drop_index(op.f('ix_user_topic_progress_topic_id'), table_name='user_topic_progress')
    op.drop_index(op.f('ix_user_topic_progress_id'), table_name='user_topic_progress')
    op.drop_table('user_topic_progress')
    # ### end Alembic commands ###
